# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e56f653b48d2caad35b9891f157c6154fe7f095384c47d0b07c7c297bd7dbb5a638c6752d1ede85c39a29fd81b919e58f57c0364a71e95e6c049b653349b993e

test:
  secret_key_base: b781d733bd9fceaf947fe25b006978e67b77f12b4e8cad3876064023fdc55aac924c8a6b2c5d2bf2069571b79ce9dcd80fb1f081896db9c1dc96e9e8d6a71050

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
